{"name": "test_C001003", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 2", "trace": "self = <test_login.Test_error object at 0x000001D8C500CB88>\n\n    def test_C001003(self):\n        print('\\n用例C001003')\n>       assert 3 == 2\nE       assert 3 == 2\n\ntestcase\\login\\test_login.py:13: AssertionError"}, "attachments": [{"name": "stdout", "source": "fbc027c0-c3e6-4dd1-b2b0-a0745dcf6f03-attachment.txt", "type": "text/plain"}], "start": 1743662233859, "stop": 1743662233860, "uuid": "5d4f4fd8-37ad-4bb3-adda-2cf88c38a3ad", "historyId": "958929d122f4809e19827bf04dfb49bb", "testCaseId": "958929d122f4809e19827bf04dfb49bb", "fullName": "testcase.login.test_login.Test_error#test_C001003", "labels": [{"name": "parentSuite", "value": "testcase.login"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_error"}, {"name": "host", "value": "DESKTOP-QOMHOVE"}, {"name": "thread", "value": "16520-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.login.test_login"}]}